### ISSUE TITLE
Why is this card not showing up?

### ISSUE THREAD

**Issue by Boogaard53** [PiotrMachowski/lovelace-google-keep-card#18]
![File-editor-Home-Assistant](https://user-images.githubusercontent.com/87951112/147024691-714a7ed0-b832-46d3-a833-6f1cf4e4d771.png)

![Configuration-Home-Assistant](https://user-images.githubusercontent.com/87951112/147024849-1ff157e2-039e-4e2e-bae4-0493fbeaf4ea.png)

![Tablet-Home-Assistant (1)](https://user-images.githubusercontent.com/87951112/147024510-8c4af182-52d1-4217-843a-fd2522b441cf.png)

**Comment by PiotrMachowski** [comment]
Does it work in incognito mode?

**Comment by Boogaard53** [comment]
> 

No it does not

**Comment by PiotrMachowski** [comment]
Ok, are there any errors in browser's console?

**Comment by Boogaard53** [comment]
Where would i find that? is that inside chrome developer tools?
If so i don't see why the issue would be in there instead of somewhere in HA

**Comment by PiotrMachowski** [comment]
Yes, inside dev tools. Frontend issues show errors there

**Comment by Boogaard53** [comment]
Somehow it works now... i didnt change anything though

**Comment by PiotrMachowski** [comment]
It's possible that you had some caching problems 👍
