### ISSUE TITLE
homeassistant cast

### ISSUE THREAD

**Issue by superharaldsson** [PiotrMachowski/lovelace-google-keep-card#2]
Awesome card. But it is not possible to use with home assistant cast!
it becomess no card type found. 
Hope you can fix this. 
/ Jonas

**Comment by PiotrMachowski** [comment]
I am glad you like it!
I have not tried HA Cast yet, definitely have to check it out

**Comment by superharaldsson** [comment]
No solutions yet?

**Comment by PiotrMachowski** [comment]
Shame on me, I forgot about this issue (still not using HA cast). Can you check the latest version (v1.0.1)?

**Comment by superharaldsson** [comment]
Understand that there is no priori when you do not use it yourself.
Unfortunately does not work in the new version either. Hope you can solve it

**Comment by PiotrMachowski** [comment]
The main problem is that I have no device to test on. 
Do you use HACS? Maybe the cards code was cached. If you don't use HACS please add `?v=1.0.1` to url in resources and check again.

**Comment by superharaldsson** [comment]
Ok 
I use HACS.

**Comment by PiotrMachowski** [comment]
So cache is not an issue. Maybe you use other custom cards that work on HA cast?

**Comment by superharaldsson** [comment]
Now it work fine
 👌

**Comment by PiotrMachowski** [comment]
That's great, especially since I haven't changed anything ;)
