### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by LEdiodes** [PiotrMachowski/lovelace-google-keep-card#24]
How do I do step 2 "Add card to resources"? Where is this done? I'm not sure where "resources:" is located. Sorry for the noob question.

**Comment by PiotrMachowski** [comment]
[Here](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#3-import-the-plugin-in-your-lovelace-config) you have a more detailed guide. If you use HACS it has probably added the card to resources automatically
