### ISSUE TITLE
hide_if_empty not working correctly?

### ISSUE THREAD

**Issue by porebas** [PiotrMachowski/lovelace-google-keep-card#4]
Thank you for the card.
I am not sure if it's just my problem, but maybe it's a bug.
When I use "hide_if_empty: true" the card hides, even when it's not empty.
![6d4051126-5d1ad900-cb7a-11e9-9adb-296df66b96a7](https://user-images.githubusercontent.com/7966774/64051525-aa4b7a80-cb7b-11e9-8c8f-6810a8aecd9a.jpg)
![640d51123-5a1fe880-cb7a-11e9-9bbf-047022b04bd7](https://user-images.githubusercontent.com/7966774/64051526-aae41100-cb7b-11e9-83a1-35ef7889a2d0.jpg)

**Comment by PiotrMachowski** [comment]
It works perfectly well on my HA. Can you define a `title` property and try again? Have you tried outside of config editor?

**Comment by porebas** [comment]
I have defined a title property and the problem is the same.
Outside of config editor the card is also not visible after changing to "hide_if_empty: true"
![Adnotacja 2019-08-31 123231](https://user-images.githubusercontent.com/7966774/64062853-807e6c00-cbec-11e9-86de-ab8ea4672c73.jpg)
![Adnotacja 2019-08-31 123315](https://user-images.githubusercontent.com/7966774/64062854-807e6c00-cbec-11e9-9f1d-b86387009c7f.jpg)

**Comment by PiotrMachowski** [comment]
Well, it turned out my HA and this repo had different versions of the card. Issue should be fixed right now, can you confirm?

**Comment by porebas** [comment]
I have just updated and now it's working great.
Thank you again for this integration.

P.S. I don't know if it was intended, but the background of the note is not transparent at alpha: 0
That's why I use 0.001 to be close to transparent

**Comment by PiotrMachowski** [comment]
That is not intended, I will check it out when possible. Could you check if `0.0` works correctly?

**Comment by porebas** [comment]
I have checked `0.0` and it's just like `0`. It's not transparent.
Need to use anything above `0` to be close to transparent.
