### ISSUE TITLE
use global theme

### ISSUE THREAD

**Issue by Juan-gimenez-globant** [PiotrMachowski/lovelace-google-keep-card#6]
This card is amazing, I'm using it to have a lot of information from google keep to my home assistant, but I'm not sure whats the use case for overriding the global theme, at least an option to not override the global theme could be handy.

**Comment by PiotrMachowski** [comment]
It is not overriding global theme: `theme` parameter is set to use appropriate colors of cards background (to match ones in Google Keep).
