### ISSUE TITLE
Theme not working.

### ISSUE THREAD

**Issue by zevulos** [PiotrMachowski/lovelace-google-keep-card#7]
When i change the theme it doesn't update the text colour, in dark theme the text should be white and in light theme it should be black but its just black all the time. The cards background changes and the alpa value works but the text colour doesnt.

**Comment by zevulos** [comment]
Seems to be fixed now 👍 thanks ! 
I really enjoy your work, keep at it :)

**Comment by PiotrMachowski** [comment]
That's nice, as I haven't changed anything ;)
